name: API + Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image for API
        run: docker build -t robot-jms:latest -f docker/Dockerfile .

      - name: Run API container with health check
        run: |
          docker run -d --network host --name api \
            --health-cmd='curl --silent --fail localhost:5000/health || exit 1' \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            robot-jms:latest

      - name: Wait for API to be ready
        run: |
          for i in {1..20}; do
            if curl --silent --fail http://localhost:5000/health; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 5
          done

          if ! curl --silent --fail http://localhost:5000/health; then
            echo "API is not ready!" >&2
            exit 1
          fi

      - name: Run Robot Tests (excluding server tests)
        run: |
          mkdir -p reports
          robot -d reports \
            tests/0.basic_tests.robot \
            tests/1.positive_tests.robot \
            tests/2.negative_tests.robot

      - name: Show path to HTML report
        run: |
          echo ""
          echo "Open test report:"
          echo "file://$PWD/reports/report.html"
          echo ""
          echo "To see logs and results, go to the reports folder:"
          ls -l reports/