name: API + Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image for API
        run: docker build -t robot-jms:latest -f docker/Dockerfile .

      - name: Run API container
        run: |
          docker run -d -p 5000:5000 --name api robot-jms:latest

      - name: Wait for API to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:5000/health && break
            echo "Waiting for API..."
            sleep 2
          done

      - name: Run Robot Tests (excluding server tests)
        run: |
          mkdir -p reports
          robot -d reports \
            tests/0.basic_tests.robot \
            tests/1.positive_tests.robot \
            tests/2.negative_tests.robot

      - name: Upload Robot Reports
        if: always()
        run: |
          if [ -d "reports" ] && [ "$(ls -A reports)" ]; then
            echo "Uploading reports..."
            tar -czf robot-reports.tar.gz reports
          else
            echo "No reports to upload."
          fi