name: API + Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      api:
        image: robot-jms:latest
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000/health || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Robot Framework and libraries
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Build Docker image for API
        run: docker build -t robot-jms:latest -f docker/Dockerfile .

      - name: Run Robot Tests (excluding server tests)
        run: |
          mkdir -p reports
          robot -d reports \
            tests/0.basic_tests.robot \
            tests/1.positive_tests.robot \
            tests/2.negative_tests.robot
        
      - name: Upload Robot Reports
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: robot-reports
          path: reports/